// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/2021/day/[challenges].tsx";
import * as $1 from "./routes/2022/day/[challenges].tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/2021/day/[challenges].tsx": $0,
    "./routes/2022/day/[challenges].tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
